function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(5)=1;
    ys_(8)=1/params(1)-1+params(2);
    KN=(ys_(8)/params(3))^(1/(params(3)-1));
    ys_(7)=(1-params(3))*KN^params(3);
    CN=KN^params(3)-params(2)*KN;
    ys_(4)=rbc_steady_state_helper(0.5,params(6),params(7),CN,ys_(7));
    ys_(3)=KN*ys_(4);
    ys_(6)=CN*ys_(4);
    ys_(1)=ys_(3)^params(3)*ys_(4)^(1-params(3));
    ys_(2)=ys_(1)-ys_(6);
    % Auxiliary equations
end
