function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(7)=0;
    ys_(8)=1/params(1)-1+params(2);
    ys_(9)=ys_(8)-params(2);
    KN=(params(3)/ys_(8))^(1/(1-params(3)));
    ys_(6)=(1-params(3))*KN^params(3);
    CN=KN^params(3)-params(2)*KN;
    ys_(5)=rbc_steady_state_helper(0.5,params(6),params(7),CN,ys_(6));
    ys_(3)=KN*ys_(5);
    ys_(2)=CN*ys_(5);
    ys_(4)=params(2)*ys_(3);
    ys_(1)=ys_(2)+ys_(4);
    ys_(10)=exp(params(7)*((1-ys_(5))^(1-params(6))-1)/(1-params(6)));
    UN=(-params(7))*(1-ys_(5))^(-params(6))*ys_(2)^(1-params(5))*ys_(10)^(1-params(5));
    UC=ys_(10)^(1-params(5))*ys_(2)^(-params(5));
    % Auxiliary equations
end
